---
title: "DHIS2 Metadata Assessment Guidance"
author: "DHIS2 Implementation Team"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    md_extensions:  -smart
  pdf_document: default
  word_document: default
always_allow_html: yes
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r include=FALSE}

if (!require("pacman")) install.packages("pacman")
pacman::p_load(jsonlite, httr, purrr,knitr,magrittr,dplyr,yaml,knitr,rmarkdown,stringi)

source("R/utils.R")

views <- transformYAMLtoControlFile() 


```


```{r sql_view_results, echo=FALSE,message=FALSE,results="asis"}

sections <- unique(views$section)

for (i in seq_along(sections)) {
  this_section <- views %>% dplyr::filter(section == sections[i])
  cat(paste("##",sections[i]))
  cat("\n")
  cat("\n")
  for (j in seq_len(NROW(this_section))) {
    cat(paste0("### ",this_section$description[j]))
    cat("\n")
    cat("\n")
    cat(stringi::stri_rand_lipsum(j)[j])
    cat("\n")
    cat("\n")
    cat("**Recommendation**")
    cat("\n")
    cat("\n")
    cat(stringi::stri_rand_lipsum(j)[j])
    cat("\n")
    cat("\n")
    cat("**Summary SQL Query**")
    cat("\n")
    cat("\n")
    cat(paste0(">",stringr::str_replace_all(this_section$summary_sql[j],"\\*","\\\\*")))
    cat("\n")
    cat("\n")
    cat("**Details SQL Query**")
    cat("\n")
    cat("\n")
    cat(paste0(">",stringr::str_replace_all(this_section$details_sql[j],"\\*","\\\\*")))
    cat("\n")
    cat("\n")
  }  
      
}

```
